# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rHTTWJfNRyiooH-zUxB69cShIRX1beFI
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url = "https://ar.wikipedia.org/wiki/كأس_العالم_2026"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print("Status Code:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

print(soup.title.text)

match_boxes = soup.select(".vevent")

print("Match Boxes Found:", len(match_boxes))

attendance = soup.find(string=re.compile(r"الحضور"))

print("Attendance text:")
print(attendance)

element = attendance.parent

for i in range(7):
    print("\nLEVEL:", i)
    print("TAG:", element.name)
    print("CLASS:", element.get("class"))
    print("TEXT:", element.get_text(" ", strip=True)[:700])

    element = element.parent

match_boxes = soup.select("div.footballbox")

print("Match Boxes Found:", len(match_boxes))

print(match_boxes[0].get_text(" ", strip=True))

print(match_boxes[0].prettify()[:5000])

matches_data = []

for match_id, box in enumerate(match_boxes, start=1):

    # Date
    date_tag = box.select_one(".bday")
    date = date_tag.get_text(strip=True) if date_tag else None

    # Time
    time_tag = box.select_one(".ftime")
    time = time_tag.get_text(" ", strip=True) if time_tag else None

    # Home Team
    home_tag = box.select_one(".fhome")
    home_team = home_tag.get_text(" ", strip=True) if home_tag else None

    # Away Team
    away_tag = box.select_one(".faway")
    away_team = away_tag.get_text(" ", strip=True) if away_tag else None

    # Score
    score_tag = box.select_one(".fscore")
    score = score_tag.get_text(" ", strip=True) if score_tag else None

    matches_data.append({
        "Match_ID": match_id,
        "Date": date,
        "Time": time,
        "Home_Team": home_team,
        "Away_Team": away_team,
        "Score": score
    })


matches_df = pd.DataFrame(matches_data)

matches_df.head(10)

def split_score(score):

    if pd.isna(score):
        return pd.Series([None, None])

    numbers = re.findall(r"\d+", str(score))

    if len(numbers) >= 2:
        return pd.Series([
            int(numbers[0]),
            int(numbers[1])
        ])

    return pd.Series([None, None])


matches_df[["Home_Score", "Away_Score"]] = matches_df["Score"].apply(split_score)

matches_df.head(10)

print("Total Matches:", len(matches_df))
print()

print(matches_df.info())

box = match_boxes[0]

for tag in box.find_all(True):
    text = tag.get_text(" ", strip=True)

    if "الحضور" in text:
        print(
            "TAG:", tag.name,
            "| CLASS:", tag.get("class"),
            "| TEXT:", text[:300]
        )

box = match_boxes[0]

location_info = box.select_one(".fleft")

print(location_info.get_text(" ", strip=True))

for i, link in enumerate(location_info.find_all("a"), start=1):
    print(i, "->", link.get_text(" ", strip=True))

links = location_info.find_all("a")

stadium = links[0].get_text(" ", strip=True)
city = links[1].get_text(" ", strip=True)

print("Stadium:", stadium)
print("City:", city)

links = location_info.find_all("a")

stadium = links[0].get_text(" ", strip=True)
city = links[1].get_text(" ", strip=True)
referee = links[2].get_text(" ", strip=True)

print("Stadium:", stadium)
print("City:", city)
print("Referee:", referee)

text = location_info.get_text(" ", strip=True)

attendance_match = re.search(r"الحضور:\s*([\d,]+)", text)

attendance = attendance_match.group(1) if attendance_match else None

print("Attendance:", attendance)

attendance = int(attendance.replace(",", ""))

print("Attendance:", attendance)
print("Type:", type(attendance))

stadiums = []
cities = []
referees = []
attendances = []

for box in match_boxes:

    location_info = box.select_one(".fleft")

    if location_info:

        links = location_info.find_all("a")

        stadium = links[0].get_text(" ", strip=True) if len(links) > 0 else None
        city = links[1].get_text(" ", strip=True) if len(links) > 1 else None
        referee = links[2].get_text(" ", strip=True) if len(links) > 2 else None

        text = location_info.get_text(" ", strip=True)

        attendance_match = re.search(r"الحضور:\s*([\d,]+)", text)

        if attendance_match:
            attendance = int(attendance_match.group(1).replace(",", ""))
        else:
            attendance = None

    else:
        stadium = None
        city = None
        referee = None
        attendance = None

    stadiums.append(stadium)
    cities.append(city)
    referees.append(referee)
    attendances.append(attendance)


matches_df["Stadium"] = stadiums
matches_df["City"] = cities
matches_df["Referee"] = referees
matches_df["Attendance"] = attendances

matches_df[
    ["Match_ID", "Home_Team", "Away_Team",
     "Stadium", "City", "Referee", "Attendance"]
].head(10)

for i in [7, 9]:
    location_info = match_boxes[i].select_one(".fleft")
    print(f"Match {i+1}:")
    print(location_info.get_text(" ", strip=True))
    print()

attendances = []

for box in match_boxes:
    location_info = box.select_one(".fleft")

    if location_info:
        text = location_info.get_text(" ", strip=True)

        attendance_match = re.search(r"الحضور:\s*([\d,،٬]+)", text)

        if attendance_match:
            attendance = re.sub(r"\D", "", attendance_match.group(1))
            attendance = int(attendance)
        else:
            attendance = None

    else:
        attendance = None

    attendances.append(attendance)

matches_df["Attendance"] = attendances

matches_df[
    ["Match_ID", "Home_Team", "Away_Team", "Attendance"]
].head(10)

for i, box in enumerate(match_boxes[:10], start=1):
    heading = box.find_previous(["h2", "h3", "h4"])

    print(
        i,
        "->",
        heading.get_text(" ", strip=True) if heading else None
    )

check_matches = [1, 6, 7, 72, 73, 88, 89, 96, 97, 100, 101, 102, 103, 104]

for match_num in check_matches:
    box = match_boxes[match_num - 1]
    heading = box.find_previous(["h2", "h3", "h4"])

    print(
        match_num,
        "->",
        heading.get_text(" ", strip=True) if heading else None
    )

group_map = {
    "المجموعة الأولى": "A",
    "المجموعة الثانية": "B",
    "المجموعة الثالثة": "C",
    "المجموعة الرابعة": "D",
    "المجموعة الخامسة": "E",
    "المجموعة السادسة": "F",
    "المجموعة السابعة": "G",
    "المجموعة الثامنة": "H",
    "المجموعة التاسعة": "I",
    "المجموعة العاشرة": "J",
    "المجموعة الحادية عشرة": "K",
    "المجموعة الثانية عشرة": "L"
}

stage_map = {
    "دور 32": "Round of 32",
    "دور 16": "Round of 16",
    "ربع النهائي": "Quarter Final",
    "نصف النهائي": "Semi Final",
    "مباراة تحديد المركز الثالث": "Third Place",
    "النهائي": "Final"
}

stages = []
groups = []

for box in match_boxes:

    heading = box.find_previous(["h2", "h3", "h4"])
    heading_text = heading.get_text(" ", strip=True)

    if heading_text in group_map:
        stage = "Group Stage"
        group = group_map[heading_text]

    else:
        stage = stage_map.get(heading_text)
        group = None

    stages.append(stage)
    groups.append(group)

matches_df["Stage"] = stages
matches_df["Group"] = groups

matches_df[
    ["Match_ID", "Stage", "Group", "Home_Team", "Away_Team"]
].head(10)

box = match_boxes[0]

home_goals = box.select_one(".fhgoal")
away_goals = box.select_one(".fagoal")

print("Home Goals:", home_goals.get_text(" ", strip=True) if home_goals else None)
print("Away Goals:", away_goals.get_text(" ", strip=True) if away_goals else None)

goal_elements = home_goals.select(".fb-goal")

for goal in goal_elements:
    scorer = goal.find_previous("a")

    print(
        "Scorer:", scorer.get_text(" ", strip=True),
        "| Minute:", goal.get_text(" ", strip=True)
    )

for i, box in enumerate(match_boxes, start=1):
    text = box.get_text(" ", strip=True)

    if "هـ.ذ." in text:
        print("Match:", i)
        print(text)
        break

box = match_boxes[7]

for goal in box.select(".fb-goal"):
    print(goal.parent.get_text(" ", strip=True))
    print("-----")

box = match_boxes[7]

for goal in box.select(".fb-goal"):

    scorer = goal.find_previous("a").get_text(" ", strip=True)
    minute = goal.get_text(" ", strip=True)

    goal_text = goal.parent.get_text(" ", strip=True)

    own_goal = "هـ.ذ." in goal_text

    print(
        "Scorer:", scorer,
        "| Minute:", minute,
        "| Own Goal:", own_goal
    )

box = match_boxes[7]

for goal in box.select(".fb-goal"):

    scorer = goal.find_previous("a").get_text(" ", strip=True)

    goal_text = goal.get_text(" ", strip=True)

    minute_match = re.search(r"\d+(?:\+\d+)?", goal_text)
    minute = minute_match.group() if minute_match else None

    own_goal = "هـ.ذ." in goal.parent.get_text(" ", strip=True)

    print(
        "Scorer:", scorer,
        "| Minute:", minute,
        "| Own Goal:", own_goal
    )

goals_data = []

goal_id = 1

for match_id, box in enumerate(match_boxes, start=1):

    home_team = matches_df.loc[match_id - 1, "Home_Team"]
    away_team = matches_df.loc[match_id - 1, "Away_Team"]

    # Home team goals
    home_goals = box.select_one(".fhgoal")

    if home_goals:
        for goal in home_goals.select(".fb-goal"):

            scorer = goal.find_previous("a").get_text(" ", strip=True)

            goal_text = goal.get_text(" ", strip=True)

            minute_match = re.search(r"\d+(?:\+\d+)?", goal_text)
            minute = minute_match.group() if minute_match else None

            own_goal = "هـ.ذ." in goal.parent.get_text(" ", strip=True)

            goals_data.append({
                "Goal_ID": goal_id,
                "Match_ID": match_id,
                "Team": home_team,
                "Scorer": scorer,
                "Minute": minute,
                "Own_Goal": own_goal
            })

            goal_id += 1

    # Away team goals
    away_goals = box.select_one(".fagoal")

    if away_goals:
        for goal in away_goals.select(".fb-goal"):

            scorer = goal.find_previous("a").get_text(" ", strip=True)

            goal_text = goal.get_text(" ", strip=True)

            minute_match = re.search(r"\d+(?:\+\d+)?", goal_text)
            minute = minute_match.group() if minute_match else None

            own_goal = "هـ.ذ." in goal.parent.get_text(" ", strip=True)

            goals_data.append({
                "Goal_ID": goal_id,
                "Match_ID": match_id,
                "Team": away_team,
                "Scorer": scorer,
                "Minute": minute,
                "Own_Goal": own_goal
            })

            goal_id += 1


goals_df = pd.DataFrame(goals_data)

goals_df.head(10)

goals_df[goals_df["Own_Goal"] == True]

def convert_minute(minute):
    minute = str(minute)

    if "+" in minute:
        base, extra = minute.split("+")
        return int(base) + int(extra)

    return int(minute)


goals_df["Exact_Minute"] = goals_df["Minute"].apply(convert_minute)

goals_df[["Scorer", "Minute", "Exact_Minute", "Own_Goal"]].head(20)

goals_df["Minute"] = goals_df["Exact_Minute"]
goals_df.drop(columns=["Exact_Minute"], inplace=True)

goals_df[["Scorer", "Minute", "Own_Goal"]].head(20)

goals_from_scores = matches_df["Home_Score"].sum() + matches_df["Away_Score"].sum()
goals_from_scraping = len(goals_df)

print("Goals from match scores:", goals_from_scores)
print("Goals extracted:", goals_from_scraping)
print("Difference:", goals_from_scores - goals_from_scraping)

goal_counts = goals_df.groupby("Match_ID").size()

check_df = matches_df[
    ["Match_ID", "Home_Team", "Away_Team", "Home_Score", "Away_Score"]
].copy()

check_df["Expected_Goals"] = (
    check_df["Home_Score"] + check_df["Away_Score"]
)

check_df["Extracted_Goals"] = (
    check_df["Match_ID"].map(goal_counts).fillna(0).astype(int)
)

check_df["Difference"] = (
    check_df["Expected_Goals"] - check_df["Extracted_Goals"]
)

check_df[check_df["Difference"] != 0]

box = match_boxes[8]   # Match 9

home_goals = box.select_one(".fhgoal")
away_goals = box.select_one(".fagoal")

print("HOME:")
print(home_goals.get_text(" | ", strip=True))
print("fb-goal count:", len(home_goals.select(".fb-goal")))

print("\nAWAY:")
print(away_goals.get_text(" | ", strip=True))
print("fb-goal count:", len(away_goals.select(".fb-goal")))

for tag in home_goals.find_all(True):
    classes = tag.get("class")
    text = tag.get_text(" ", strip=True)

    if classes and text:
        print(
            "TAG:", tag.name,
            "| CLASS:", classes,
            "| TEXT:", text
        )

for text_node in home_goals.find_all(string=True):

    text = text_node.strip()

    if text:
        print(
            "TEXT:", repr(text),
            "| TAG:", text_node.parent.name,
            "| CLASS:", text_node.parent.get("class")
        )

from bs4 import BeautifulSoup

html = str(home_goals)

parts = re.split(r"<br\s*/?>", html)

for part in parts:
    part_soup = BeautifulSoup(part, "html.parser")
    text = part_soup.get_text(" ", strip=True)

    if not text:
        continue

    scorer_tag = part_soup.find("a")
    scorer = scorer_tag.get_text(" ", strip=True) if scorer_tag else None

    minute_match = re.search(r"\d+(?:\+\d+)?", text)
    minute = minute_match.group() if minute_match else None

    own_goal = "هـ.ذ." in text

    print(
        "Scorer:", scorer,
        "| Minute:", minute,
        "| Own Goal:", own_goal
    )

print("Direct BR count:", len(home_goals.find_all("br", recursive=False)))

for i, child in enumerate(home_goals.children):
    if getattr(child, "name", None) == "br":
        print(i, "-> BR")
    else:
        text = str(child).strip()
        if text:
            print(i, "->", text[:150])

goal_items = home_goals.find_all("li")

print("Goal items:", len(goal_items))

for i, item in enumerate(goal_items, start=1):
    print(i, "->", item.get_text(" ", strip=True))

for item in goal_items:

    scorer = item.find("a").get_text(" ", strip=True)

    text = item.get_text(" ", strip=True)

    minutes = re.findall(r"\d+(?:\+\d+)?(?=')", text)

    for minute in minutes:
        print(
            "Scorer:", scorer,
            "| Minute:", minute
        )

goals_data = []
goal_id = 1

for match_id, box in enumerate(match_boxes, start=1):

    home_team = matches_df.loc[match_id - 1, "Home_Team"]
    away_team = matches_df.loc[match_id - 1, "Away_Team"]

    # Home goals + Away goals
    sides = [
        (".fhgoal", home_team),
        (".fagoal", away_team)
    ]

    for selector, team in sides:

        goals_section = box.select_one(selector)

        if not goals_section:
            continue

        goal_items = goals_section.find_all("li")

        for item in goal_items:

            scorer_tag = item.find("a")

            if not scorer_tag:
                continue

            scorer = scorer_tag.get_text(" ", strip=True)

            text = item.get_text(" ", strip=True)

            # ممكن نفس اللاعب يكون مسجل أكتر من هدف
            minutes = re.findall(r"\d+(?:\+\d+)?(?=')", text)

            own_goal = "هـ.ذ." in text

            for minute in minutes:

                # تحويل 90+4 إلى 94
                if "+" in minute:
                    base, extra = minute.split("+")
                    exact_minute = int(base) + int(extra)
                else:
                    exact_minute = int(minute)

                goals_data.append({
                    "Goal_ID": goal_id,
                    "Match_ID": match_id,
                    "Team": team,
                    "Scorer": scorer,
                    "Minute": exact_minute,
                    "Own_Goal": own_goal
                })

                goal_id += 1


goals_df = pd.DataFrame(goals_data)

goals_df.head(20)

for match_num in [1, 2, 3, 9]:

    box = match_boxes[match_num - 1]

    print("Match:", match_num)

    for selector in [".fhgoal", ".fagoal"]:

        section = box.select_one(selector)

        if section:
            print(
                selector,
                "| li:", len(section.find_all("li")),
                "| fb-goal:", len(section.select(".fb-goal")),
                "| Text:", section.get_text(" ", strip=True)
            )

    print("-----")

goals_data = []
goal_id = 1

for match_id, box in enumerate(match_boxes, start=1):

    home_team = matches_df.loc[match_id - 1, "Home_Team"]
    away_team = matches_df.loc[match_id - 1, "Away_Team"]

    sides = [
        (".fhgoal", home_team),
        (".fagoal", away_team)
    ]

    for selector, team in sides:

        section = box.select_one(selector)

        if not section:
            continue

        # 1) Goals inside <li>
        for item in section.find_all("li"):

            scorer_tag = item.find("a")

            if not scorer_tag:
                continue

            scorer = scorer_tag.get_text(" ", strip=True)
            text = item.get_text(" ", strip=True)

            minutes = re.findall(r"\d+(?:\+\d+)?(?=')", text)

            own_goal = "هـ.ذ." in text

            for minute in minutes:

                if "+" in minute:
                    base, extra = minute.split("+")
                    exact_minute = int(base) + int(extra)
                else:
                    exact_minute = int(minute)

                goals_data.append({
                    "Goal_ID": goal_id,
                    "Match_ID": match_id,
                    "Team": team,
                    "Scorer": scorer,
                    "Minute": exact_minute,
                    "Own_Goal": own_goal
                })

                goal_id += 1


        # 2) fb-goal elements that are NOT inside <li>
        for goal in section.select(".fb-goal"):

            if goal.find_parent("li"):
                continue

            scorer_tag = goal.find_previous("a")

            if not scorer_tag:
                continue

            scorer = scorer_tag.get_text(" ", strip=True)

            text = goal.get_text(" ", strip=True)

            minute_match = re.search(r"\d+(?:\+\d+)?", text)

            if not minute_match:
                continue

            minute = minute_match.group()

            if "+" in minute:
                base, extra = minute.split("+")
                exact_minute = int(base) + int(extra)
            else:
                exact_minute = int(minute)

            own_goal = "هـ.ذ." in goal.parent.get_text(" ", strip=True)

            goals_data.append({
                "Goal_ID": goal_id,
                "Match_ID": match_id,
                "Team": team,
                "Scorer": scorer,
                "Minute": exact_minute,
                "Own_Goal": own_goal
            })

            goal_id += 1


goals_df = pd.DataFrame(goals_data)

print("Goals Extracted:", len(goals_df))

goal_counts = goals_df.groupby("Match_ID").size()

check_df = matches_df[
    ["Match_ID", "Home_Team", "Away_Team", "Home_Score", "Away_Score"]
].copy()

check_df["Expected_Goals"] = (
    check_df["Home_Score"] + check_df["Away_Score"]
)

check_df["Extracted_Goals"] = (
    check_df["Match_ID"].map(goal_counts).fillna(0).astype(int)
)

check_df["Difference"] = (
    check_df["Expected_Goals"] - check_df["Extracted_Goals"]
)

check_df[check_df["Difference"] != 0]

box = match_boxes[15]   # Match 16

home_goals = box.select_one(".fhgoal")
away_goals = box.select_one(".fagoal")

print("HOME:")
print(home_goals.get_text(" | ", strip=True) if home_goals else None)
print("li count:", len(home_goals.find_all("li")) if home_goals else 0)
print("fb-goal count:", len(home_goals.select(".fb-goal")) if home_goals else 0)

print("\nAWAY:")
print(away_goals.get_text(" | ", strip=True) if away_goals else None)
print("li count:", len(away_goals.find_all("li")) if away_goals else 0)
print("fb-goal count:", len(away_goals.select(".fb-goal")) if away_goals else 0)

for text_node in home_goals.find_all(string=True):

    text = text_node.strip()

    if text:
        print(
            "TEXT:", repr(text),
            "| TAG:", text_node.parent.name,
            "| CLASS:", text_node.parent.get("class")
        )

for i, link in enumerate(home_goals.find_all("a"), start=1):
    print(
        i,
        "->",
        link.get_text(" ", strip=True),
        "| title:",
        link.get("title")
    )

from bs4 import NavigableString

player_links = home_goals.find_all("a")

for i, player in enumerate(player_links):

    scorer = player.get_text(" ", strip=True)

    next_player = player_links[i + 1] if i + 1 < len(player_links) else None

    parts = []

    for element in player.next_elements:

        if next_player is not None and element is next_player:
            break

        if isinstance(element, NavigableString):
            text = str(element).strip()

            if text:
                parts.append(text)

    player_text = " ".join(parts)

    minutes = re.findall(r"\d+(?:\+\d+)?(?=')", player_text)

    print(
        "Scorer:", scorer,
        "| Minutes:", minutes
    )

from bs4 import NavigableString

elements = list(home_goals.descendants)
player_links = home_goals.find_all("a")

for i, player in enumerate(player_links):

    scorer = player.get_text(" ", strip=True)

    start = elements.index(player) + 1

    if i + 1 < len(player_links):
        end = elements.index(player_links[i + 1])
    else:
        end = len(elements)

    parts = []

    for element in elements[start:end]:

        if isinstance(element, NavigableString):
            text = str(element).strip()

            if text:
                parts.append(text)

    player_text = " ".join(parts)

    minutes = re.findall(r"\d+(?:\+\d+)?(?=')", player_text)

    print(
        "Scorer:", scorer,
        "| Minutes:", minutes
    )

player_links = [
    link for link in home_goals.find_all("a")
    if "هـ.ذ." not in link.get_text(" ", strip=True)
]

for link in player_links:
    print(link.get_text(" ", strip=True))

for link in player_links:
    print(link.get_text(" ", strip=True), "->", link.get("href"))

player_data = []

for link in player_links:
    player_data.append({
        "Player": link.get_text(" ", strip=True),
        "URL": link.get("href")
    })

player_data

for item in home_goals.stripped_strings:
    print(repr(item))

goal_items = list(home_goals.stripped_strings)

player_names = [p["Player"] for p in player_data]

goals = []
current_player = None

for item in goal_items:
    text = item.strip()

    if text in player_names:
        current_player = text

    elif current_player:
        minute = "".join(
            char for char in text
            if char.isdigit() or char == "+"
        )

        if minute:
            goals.append({
                "Player": current_player,
                "Minute": minute
            })

goals

for goal in goals:
    minute = goal["Minute"]

    if "+" in minute:
        parts = minute.split("+")
        minute = parts[1] + "+" + parts[0]

    goal["Minute"] = minute

goals

player_url_map = {
    p["Player"]: p["URL"]
    for p in player_data
}

for goal in goals:
    goal["URL"] = player_url_map.get(goal["Player"])

goals

import pandas as pd

goals_df = pd.DataFrame(goals)

goals_df

for item in away_goals.stripped_strings:
    print(repr(item))

print(away_goals)

print(away_goals.parent.get_text(" | ", strip=True))

for cell in away_goals.parent.find_all(["th", "td"], recursive=False):
    print(cell.get("class"), "->", repr(cell.get_text(" ", strip=True)))

away_goal_items = list(away_goals.stripped_strings)

print(away_goal_items)

import re

def parse_goals(goal_cell):
    if goal_cell is None:
        return []

    player_links = [
        link for link in goal_cell.find_all("a")
        if not re.fullmatch(r"[\d+\s']+", link.get_text(" ", strip=True))
    ]

    player_names = [
        link.get_text(" ", strip=True)
        for link in player_links
    ]

    player_url_map = {
        link.get_text(" ", strip=True): link.get("href")
        for link in player_links
    }

    goal_items = list(goal_cell.stripped_strings)

    goals_list = []
    current_player = None

    for item in goal_items:
        text = item.strip()

        if text in player_names:
            current_player = text

        elif current_player:
            minute = "".join(
                char for char in text
                if char.isdigit() or char == "+"
            )

            if minute:
                if "+" in minute:
                    parts = minute.split("+")
                    minute = parts[1] + "+" + parts[0]

                goals_list.append({
                    "Player": current_player,
                    "Minute": minute,
                    "URL": player_url_map.get(current_player)
                })

    return goals_list


print("HOME:")
print(parse_goals(home_goals))

print("\nAWAY:")
print(parse_goals(away_goals))

match_rows = [
    row for row in soup.find_all("tr")
    if row.find("td", class_="fghoal")
    or row.find("td", class_="fagoal")
]

print("Number of match rows:", len(match_rows))

for i, row in enumerate(match_rows[:5], 1):
    print(i, "->", row.get_text(" | ", strip=True))

for i, row in enumerate(match_rows, 1):
    heading = row.find_previous(["h2", "h3", "h4"])

    heading_text = (
        heading.get_text(" ", strip=True)
        if heading
        else "NO HEADING"
    )

    print(i, "->", heading_text)

for i, row in enumerate(match_rows, 1):
    if 73 <= i <= 100:
        heading = row.find_previous(["h2", "h3", "h4"])
        heading_text = heading.get_text(" ", strip=True) if heading else ""

        print(
            i,
            "|",
            heading_text,
            "|",
            repr(row.get_text(" | ", strip=True))
        )

real_match_rows = []

for row in match_rows:
    has_report = any(
        "تقرير" in link.get_text(" ", strip=True)
        for link in row.find_all("a")
    )

    if has_report:
        real_match_rows.append(row)

print("Real matches:", len(real_match_rows))

first_match = real_match_rows[0]

for i, cell in enumerate(first_match.find_all(["th", "td"], recursive=False)):
    print(
        i,
        "| class =", cell.get("class"),
        "| text =", repr(cell.get_text(" ", strip=True))
    )

match_info_row = first_match.find_previous_sibling("tr")

for i, cell in enumerate(
    match_info_row.find_all(["th", "td"], recursive=False)
):
    print(
        i,
        "| class =", cell.get("class"),
        "| text =", repr(cell.get_text(" ", strip=True))
    )

row = match_info_row

for step in range(1, 4):
    row = row.find_previous_sibling("tr")

    if row:
        print(
            "STEP", step,
            "->",
            repr(row.get_text(" | ", strip=True))
        )

parent = match_info_row.parent

for i, row in enumerate(parent.find_all("tr", recursive=False)):
    print(i, "->", repr(row.get_text(" | ", strip=True)))

node = match_info_row

for level in range(1, 6):
    node = node.parent

    if node is None:
        break

    print(
        "LEVEL", level,
        "| tag =", node.name,
        "| class =", node.get("class"),
        "| text =", repr(node.get_text(" | ", strip=True)[:500])
    )

footballbox = match_info_row.find_parent("div", class_="footballbox")

for i, child in enumerate(footballbox.find_all(recursive=False)):
    print(
        i,
        "| tag =", child.name,
        "| class =", child.get("class"),
        "| text =", repr(child.get_text(" | ", strip=True))
    )

fright = footballbox.find("div", class_="fright")
fleft = footballbox.find("div", class_="fleft")

print("=== FRIGHT ===")

for i, child in enumerate(fright.find_all(recursive=False)):
    print(
        i,
        "| tag =", child.name,
        "| class =", child.get("class"),
        "| text =", repr(child.get_text(" ", strip=True))
    )

print("\n=== FLEFT ===")

for i, child in enumerate(fleft.find_all(recursive=False)):
    print(
        i,
        "| tag =", child.name,
        "| class =", child.get("class"),
        "| text =", repr(child.get_text(" ", strip=True))
    )

from datetime import datetime
import re

time_text = time_tag.get_text(" ", strip=True)

date_iso = re.search(r"\d{4}-\d{2}-\d{2}", time_text).group()

short_date = datetime.strptime(date_iso, "%Y-%m-%d").strftime("%d/%m/%Y")

print(short_date)

from datetime import datetime
import re
import unicodedata

time_text = time_tag.get_text(" ", strip=True)

# نشيل علامات اتجاه النص المخفية
clean_text = "".join(
    char for char in time_text
    if unicodedata.category(char) != "Cf"
)

date_match = re.search(r"\d{4}\s*-\s*\d{2}\s*-\s*\d{2}", clean_text)

print("Original:", repr(time_text))
print("Clean:", repr(clean_text))
print("Match:", date_match)

first_match = real_match_rows[0]

footballbox = first_match.find_parent("div", class_="footballbox")
fright = footballbox.find("div", class_="fright")

print(repr(fright.get_text(" ", strip=True)))

from datetime import datetime
import re

fright_text = fright.get_text(" ", strip=True)

date_iso = re.search(r"\d{4}-\d{2}-\d{2}", fright_text).group(0)

short_date = datetime.strptime(date_iso, "%Y-%m-%d").strftime("%d/%m/%Y")

print(short_date)

def get_short_date(footballbox):
    fright = footballbox.find("div", class_="fright")

    if fright is None:
        return None

    text = fright.get_text(" ", strip=True)

    date_match = re.search(r"\d{4}-\d{2}-\d{2}", text)

    if date_match is None:
        return None

    return datetime.strptime(
        date_match.group(0),
        "%Y-%m-%d"
    ).strftime("%d/%m/%Y")


# Test first 5 matches
for i, row in enumerate(real_match_rows[:5], 1):
    footballbox = row.find_parent("div", class_="footballbox")

    print(i, "->", get_short_date(footballbox))

def get_match_time(footballbox):
    fright = footballbox.find("div", class_="fright")

    if fright is None:
        return None

    text = fright.get_text(" ", strip=True)

    time_match = re.search(
        r"(\d{1,2}:\d{2})\s*([صم])",
        text
    )

    if time_match is None:
        return None

    clock = time_match.group(1)
    period = time_match.group(2)

    hour, minute = map(int, clock.split(":"))

    if period == "م" and hour != 12:
        hour += 12

    if period == "ص" and hour == 12:
        hour = 0

    return f"{hour:02d}:{minute:02d}"


for i, row in enumerate(real_match_rows[:5], 1):
    footballbox = row.find_parent("div", class_="footballbox")

    print(
        i,
        "->",
        get_short_date(footballbox),
        "|",
        get_match_time(footballbox)
    )

first_match = real_match_rows[0]

footballbox = first_match.find_parent("div", class_="footballbox")

# Match info row
match_info_row = first_match.find_previous_sibling("tr")

home_team = match_info_row.find("td", class_="fhome").get_text(" ", strip=True)
score = match_info_row.find("td", class_="fscore").get_text(" ", strip=True)
away_team = match_info_row.find("td", class_="faway").get_text(" ", strip=True)

match_record = {
    "Date": get_short_date(footballbox),
    "Time": get_match_time(footballbox),
    "Home Team": home_team,
    "Score": score,
    "Away Team": away_team,
    "Home Goals": parse_goals(
        first_match.find("td", class_="fhgoal")
    ),
    "Away Goals": parse_goals(
        first_match.find("td", class_="fagoal")
    )
}

match_record

tbody = first_match.find_parent("tbody")

match_info_row = tbody.find(
    "tr",
    string=lambda x: False
)

for row in tbody.find_all("tr", recursive=False):
    if row.find("td", class_="fhome"):
        match_info_row = row
        break

print(match_info_row.get_text(" | ", strip=True))

first_match = real_match_rows[0]

tbody = first_match.find_parent("tbody")

for row in tbody.find_all("tr", recursive=False):
    home = row.find(class_="fhome")
    score = row.find(class_="fscore")
    away = row.find(class_="faway")

    if home and score and away:
        match_info_row = row

        print("Home:", home.get_text(" ", strip=True))
        print("Score:", score.get_text(" ", strip=True))
        print("Away:", away.get_text(" ", strip=True))

first_match = real_match_rows[0]

footballbox = first_match.find_parent("div", class_="footballbox")
tbody = first_match.find_parent("tbody")

# Find teams + score row
match_info_row = None

for row in tbody.find_all("tr", recursive=False):
    home = row.find(class_="fhome")
    score = row.find(class_="fscore")
    away = row.find(class_="faway")

    if home and score and away:
        match_info_row = row
        break


home_team = match_info_row.find(class_="fhome").get_text(" ", strip=True)
score = match_info_row.find(class_="fscore").get_text(" ", strip=True)
away_team = match_info_row.find(class_="faway").get_text(" ", strip=True)


home_goal_cell = first_match.find(class_="fhgoal")
away_goal_cell = first_match.find(class_="fagoal")


match_record = {
    "Date": get_short_date(footballbox),
    "Time": get_match_time(footballbox),
    "Home Team": home_team,
    "Score": score,
    "Away Team": away_team,
    "Home Goals": parse_goals(home_goal_cell),
    "Away Goals": parse_goals(away_goal_cell)
}

match_record

fleft = footballbox.find("div", class_="fleft")

details = fleft.find_all("div", recursive=False)

# Stadium + City
venue_div = details[0]
venue_links = venue_div.find_all("a")

stadium = (
    venue_links[0].get_text(" ", strip=True)
    if len(venue_links) >= 1
    else None
)

city = (
    venue_links[1].get_text(" ", strip=True)
    if len(venue_links) >= 2
    else None
)

# Attendance
attendance_text = details[1].get_text(" ", strip=True)

attendance_match = re.search(r"[\d,]+", attendance_text)

attendance = (
    int(attendance_match.group().replace(",", ""))
    if attendance_match
    else None
)

# Referee
referee_div = details[2]
referee_links = referee_div.find_all("a")

referee = (
    referee_links[0].get_text(" ", strip=True)
    if referee_links
    else None
)

print("Stadium:", stadium)
print("City:", city)
print("Attendance:", attendance)
print("Referee:", referee)

match_record["Stadium"] = stadium
match_record["City"] = city
match_record["Attendance"] = attendance
match_record["Referee"] = referee

match_record

def build_match_record(goal_row):
    footballbox = goal_row.find_parent("div", class_="footballbox")
    tbody = goal_row.find_parent("tbody")

    # -------------------------
    # Teams + Score
    # -------------------------
    match_info_row = None

    for row in tbody.find_all("tr", recursive=False):
        home = row.find(class_="fhome")
        score = row.find(class_="fscore")
        away = row.find(class_="faway")

        if home and score and away:
            match_info_row = row
            break

    if match_info_row is None:
        return None

    home_team = match_info_row.find(
        class_="fhome"
    ).get_text(" ", strip=True)

    score = match_info_row.find(
        class_="fscore"
    ).get_text(" ", strip=True)

    away_team = match_info_row.find(
        class_="faway"
    ).get_text(" ", strip=True)

    # -------------------------
    # Goals
    # -------------------------
    home_goal_cell = goal_row.find(class_="fhgoal")
    away_goal_cell = goal_row.find(class_="fagoal")

    home_goals = parse_goals(home_goal_cell)
    away_goals = parse_goals(away_goal_cell)

    # -------------------------
    # Venue Details
    # -------------------------
    stadium = None
    city = None
    attendance = None
    referee = None

    fleft = footballbox.find("div", class_="fleft")

    if fleft:
        details = fleft.find_all("div", recursive=False)

        # Stadium + City
        if len(details) >= 1:
            venue_links = details[0].find_all("a")

            if len(venue_links) >= 1:
                stadium = venue_links[0].get_text(
                    " ", strip=True
                )

            if len(venue_links) >= 2:
                city = venue_links[1].get_text(
                    " ", strip=True
                )

        # Attendance
        if len(details) >= 2:
            attendance_text = details[1].get_text(
                " ", strip=True
            )

            attendance_match = re.search(
                r"[\d,]+",
                attendance_text
            )

            if attendance_match:
                attendance = int(
                    attendance_match
                    .group()
                    .replace(",", "")
                )

        # Referee
        if len(details) >= 3:
            referee_links = details[2].find_all("a")

            if referee_links:
                referee = referee_links[0].get_text(
                    " ", strip=True
                )

    # -------------------------
    # Round / Stage
    # -------------------------
    heading = footballbox.find_previous(
        ["h2", "h3", "h4"]
    )

    stage = (
        heading.get_text(" ", strip=True)
        if heading
        else None
    )

    # -------------------------
    # Final Record
    # -------------------------
    return {
        "Date": get_short_date(footballbox),
        "Time": get_match_time(footballbox),
        "Stage": stage,
        "Home Team": home_team,
        "Score": score,
        "Away Team": away_team,
        "Home Goals": home_goals,
        "Away Goals": away_goals,
        "Stadium": stadium,
        "City": city,
        "Attendance": attendance,
        "Referee": referee
    }

test_match = build_match_record(real_match_rows[0])

test_match

all_matches = []

for row in real_match_rows:
    record = build_match_record(row)

    if record is not None:
        all_matches.append(record)

print("Total matches extracted:", len(all_matches))

all_matches[:3]

matches_df = pd.DataFrame(all_matches)

print("Total Rows:", len(matches_df))

print("\nMissing Values:")
print(
    matches_df[
        [
            "Date",
            "Time",
            "Stage",
            "Home Team",
            "Score",
            "Away Team",
            "Stadium",
            "City",
            "Attendance",
            "Referee"
        ]
    ].isna().sum()
)

print("\nDuplicate Matches:")
print(
    matches_df.duplicated(
        subset=[
            "Date",
            "Home Team",
            "Away Team"
        ]
    ).sum()
)

goal_count_issues = []

for i, match in enumerate(all_matches, 1):

    # Extract the actual match score
    score_numbers = re.findall(r"\d+", match["Score"])

    if len(score_numbers) < 2:
        goal_count_issues.append({
            "Match": i,
            "Home Team": match["Home Team"],
            "Away Team": match["Away Team"],
            "Score": match["Score"],
            "Issue": "Could not parse score"
        })
        continue

    expected_home = int(score_numbers[0])
    expected_away = int(score_numbers[1])

    extracted_home = len(match["Home Goals"])
    extracted_away = len(match["Away Goals"])

    if (
        expected_home != extracted_home
        or expected_away != extracted_away
    ):
        goal_count_issues.append({
            "Match": i,
            "Home Team": match["Home Team"],
            "Away Team": match["Away Team"],
            "Score": match["Score"],
            "Expected Home": expected_home,
            "Extracted Home": extracted_home,
            "Expected Away": expected_away,
            "Extracted Away": extracted_away
        })


print("Goal count mismatches:", len(goal_count_issues))

for issue in goal_count_issues:
    print(issue)

problem_row = real_match_rows[44]   # Match 45

footballbox = problem_row.find_parent("div", class_="footballbox")
tbody = problem_row.find_parent("tbody")

print("=== MATCH INFO ===")

for row in tbody.find_all("tr", recursive=False):
    home = row.find(class_="fhome")
    score = row.find(class_="fscore")
    away = row.find(class_="faway")

    if home and score and away:
        print("Home:", home.get_text(" ", strip=True))
        print("Score:", score.get_text(" ", strip=True))
        print("Away:", away.get_text(" ", strip=True))

print("\n=== GOAL CELLS ===")

fhgoal = problem_row.find(class_="fhgoal")
fagoal = problem_row.find(class_="fagoal")

print(
    "fhgoal:",
    repr(fhgoal.get_text(" | ", strip=True)) if fhgoal else None
)

print(
    "fagoal:",
    repr(fagoal.get_text(" | ", strip=True)) if fagoal else None
)

def get_correct_score(match):
    score_numbers = re.findall(r"\d+", match["Score"])

    if len(score_numbers) < 2:
        return match["Score"]

    first = int(score_numbers[0])
    second = int(score_numbers[1])

    home_goals = len(match["Home Goals"])
    away_goals = len(match["Away Goals"])

    # Normal orientation
    if first == home_goals and second == away_goals:
        return f"{first}-{second}"

    # RTL reversed orientation
    if second == home_goals and first == away_goals:
        return f"{second}-{first}"

    # Leave untouched if neither matches
    return match["Score"]


problem_match = all_matches[44]

print("Original Score:", problem_match["Score"])
print("Correct Score:", get_correct_score(problem_match))

for match in all_matches:
    match["Score"] = get_correct_score(match)

goal_count_issues = []

for i, match in enumerate(all_matches, 1):

    score_numbers = re.findall(r"\d+", match["Score"])

    if len(score_numbers) < 2:
        goal_count_issues.append({
            "Match": i,
            "Home Team": match["Home Team"],
            "Away Team": match["Away Team"],
            "Score": match["Score"],
            "Issue": "Could not parse score"
        })
        continue

    expected_home = int(score_numbers[0])
    expected_away = int(score_numbers[1])

    extracted_home = len(match["Home Goals"])
    extracted_away = len(match["Away Goals"])

    if (
        expected_home != extracted_home
        or expected_away != extracted_away
    ):
        goal_count_issues.append({
            "Match": i,
            "Home Team": match["Home Team"],
            "Away Team": match["Away Team"],
            "Score": match["Score"],
            "Expected Home": expected_home,
            "Extracted Home": extracted_home,
            "Expected Away": expected_away,
            "Extracted Away": extracted_away
        })

print("Goal count mismatches:", len(goal_count_issues))

for issue in goal_count_issues:
    print(issue)

goals_records = []

for match_id, match in enumerate(all_matches, 1):

    # Home Goals
    for goal in match["Home Goals"]:
        goals_records.append({
            "Match ID": match_id,
            "Date": match["Date"],
            "Stage": match["Stage"],
            "Team": match["Home Team"],
            "Opponent": match["Away Team"],
            "Home/Away": "Home",
            "Player": goal["Player"],
            "Minute": goal["Minute"],
            "Player URL": goal["URL"],
            "Score": match["Score"]
        })

    # Away Goals
    for goal in match["Away Goals"]:
        goals_records.append({
            "Match ID": match_id,
            "Date": match["Date"],
            "Stage": match["Stage"],
            "Team": match["Away Team"],
            "Opponent": match["Home Team"],
            "Home/Away": "Away",
            "Player": goal["Player"],
            "Minute": goal["Minute"],
            "Player URL": goal["URL"],
            "Score": match["Score"]
        })


goals_df = pd.DataFrame(goals_records)

print("Total goals:", len(goals_df))

goals_df.head(10)

expected_total_goals = 0

for match in all_matches:
    score_numbers = re.findall(r"\d+", match["Score"])

    if len(score_numbers) == 2:
        home_score = int(score_numbers[0])
        away_score = int(score_numbers[1])

        expected_total_goals += home_score + away_score


print("Goals from match scores:", expected_total_goals)
print("Goals extracted:", len(goals_df))
print("Difference:", len(goals_df) - expected_total_goals)

special_goal_cases = []

for match_id, row in enumerate(real_match_rows, 1):

    for side, goal_class in [
        ("Home", "fhgoal"),
        ("Away", "fagoal")
    ]:
        cell = row.find(class_=goal_class)

        if cell is None:
            continue

        text = cell.get_text(" ", strip=True)

        if "ر.ج." in text or "هـ.ذ." in text:
            special_goal_cases.append({
                "Match ID": match_id,
                "Side": side,
                "Text": text
            })


print("Special goal cells:", len(special_goal_cases))

for case in special_goal_cases:
    print(
        case["Match ID"],
        "|",
        case["Side"],
        "|",
        case["Text"]
    )

import re

def parse_goals(goal_cell):
    if goal_cell is None:
        return []

    player_links = [
        link for link in goal_cell.find_all("a")
        if not re.fullmatch(
            r"[\d+\s']+",
            link.get_text(" ", strip=True)
        )
    ]

    player_names = [
        link.get_text(" ", strip=True)
        for link in player_links
    ]

    player_url_map = {
        link.get_text(" ", strip=True): link.get("href")
        for link in player_links
    }

    goal_items = list(goal_cell.stripped_strings)

    goals_list = []
    current_player = None

    for item in goal_items:
        text = item.strip()

        # -------------------------
        # Player
        # -------------------------
        if text in player_names:
            current_player = text
            continue

        # -------------------------
        # Penalty
        # -------------------------
        if "ر.ج." in text:
            if goals_list:
                goals_list[-1]["Goal Type"] = "Penalty"
            continue

        # -------------------------
        # Own Goal
        # -------------------------
        if "هـ.ذ." in text:
            if goals_list:
                goals_list[-1]["Goal Type"] = "Own Goal"
            continue

        # -------------------------
        # Minute
        # -------------------------
        if current_player:
            minute = "".join(
                char for char in text
                if char.isdigit() or char == "+"
            )

            if minute:
                # Arabic RTL correction
                if "+" in minute:
                    parts = minute.split("+")

                    if len(parts) == 2:
                        minute = parts[1] + "+" + parts[0]

                goals_list.append({
                    "Player": current_player,
                    "Minute": minute,
                    "Goal Type": "Normal",
                    "URL": player_url_map.get(current_player)
                })

    return goals_list

all_matches = []

for row in real_match_rows:
    record = build_match_record(row)

    if record is not None:
        all_matches.append(record)

print("Matches rebuilt:", len(all_matches))

for match in all_matches:
    match["Score"] = get_correct_score(match)

print("Match 45:")
print(all_matches[44]["Home Goals"])

import re
import unicodedata

def clean_unicode_text(text):
    return "".join(
        char for char in text
        if unicodedata.category(char) != "Cf"
    )


def parse_goals(goal_cell):
    if goal_cell is None:
        return []

    player_links = [
        link for link in goal_cell.find_all("a")
        if not re.fullmatch(
            r"[\d+\s']+",
            clean_unicode_text(
                link.get_text(" ", strip=True)
            )
        )
    ]

    player_names = [
        clean_unicode_text(
            link.get_text(" ", strip=True)
        )
        for link in player_links
    ]

    player_url_map = {
        clean_unicode_text(
            link.get_text(" ", strip=True)
        ): link.get("href")
        for link in player_links
    }

    goal_items = list(goal_cell.stripped_strings)

    goals_list = []
    current_player = None

    for item in goal_items:

        text = clean_unicode_text(item.strip())

        # نسخة بدون مسافات
        compact_text = text.replace(" ", "")

        # -------------------------
        # Player
        # -------------------------
        if text in player_names:
            current_player = text
            continue

        # -------------------------
        # Penalty
        # -------------------------
        if "ر.ج." in compact_text:
            if goals_list:
                goals_list[-1]["Goal Type"] = "Penalty"
            continue

        # -------------------------
        # Own Goal
        # -------------------------
        if "هـ.ذ." in compact_text:
            if goals_list:
                goals_list[-1]["Goal Type"] = "Own Goal"
            continue

        # -------------------------
        # Minute
        # -------------------------
        if current_player:
            minute = "".join(
                char for char in text
                if char.isdigit() or char == "+"
            )

            if minute:

                if "+" in minute:
                    parts = minute.split("+")

                    if len(parts) == 2:
                        minute = parts[1] + "+" + parts[0]

                goals_list.append({
                    "Player": current_player,
                    "Minute": minute,
                    "Goal Type": "Normal",
                    "URL": player_url_map.get(current_player)
                })

    return goals_list

all_matches = []

for row in real_match_rows:
    record = build_match_record(row)

    if record is not None:
        all_matches.append(record)

for match in all_matches:
    match["Score"] = get_correct_score(match)

print(all_matches[44]["Home Goals"])

import re
import unicodedata


def clean_unicode_text(text):
    return "".join(
        char for char in text
        if unicodedata.category(char) != "Cf"
    )


def parse_goals(goal_cell):
    if goal_cell is None:
        return []

    # -------------------------
    # Player Links
    # -------------------------
    player_links = []

    for link in goal_cell.find_all("a"):

        name = clean_unicode_text(
            link.get_text(" ", strip=True)
        )

        compact = name.replace(" ", "")

        # Ignore penalty / own-goal markers
        if compact in {"ر.ج.", "هـ.ذ."}:
            continue

        # Ignore minute-only links
        if re.fullmatch(r"[\d+\s']+", name):
            continue

        player_links.append(link)

    player_names = [
        clean_unicode_text(
            link.get_text(" ", strip=True)
        )
        for link in player_links
    ]

    player_url_map = {
        clean_unicode_text(
            link.get_text(" ", strip=True)
        ): link.get("href")
        for link in player_links
    }

    goal_items = list(goal_cell.stripped_strings)

    goals_list = []
    current_player = None

    for item in goal_items:

        text = clean_unicode_text(item.strip())
        compact_text = text.replace(" ", "")

        # -------------------------
        # Penalty
        # -------------------------
        if compact_text == "ر.ج.":
            if goals_list:
                goals_list[-1]["Goal Type"] = "Penalty"
            continue

        # -------------------------
        # Own Goal
        # -------------------------
        if compact_text == "هـ.ذ.":
            if goals_list:
                goals_list[-1]["Goal Type"] = "Own Goal"
            continue

        # -------------------------
        # Player
        # -------------------------
        if text in player_names:
            current_player = text
            continue

        # -------------------------
        # Minute
        # -------------------------
        if current_player:

            minute = "".join(
                char for char in text
                if char.isdigit() or char == "+"
            )

            if minute:

                if "+" in minute:
                    parts = minute.split("+")

                    if len(parts) == 2:
                        minute = parts[1] + "+" + parts[0]

                goals_list.append({
                    "Player": current_player,
                    "Minute": minute,
                    "Goal Type": "Normal",
                    "URL": player_url_map.get(current_player)
                })

    return goals_list

all_matches = []

for row in real_match_rows:
    record = build_match_record(row)

    if record is not None:
        all_matches.append(record)

for match in all_matches:
    match["Score"] = get_correct_score(match)

all_matches[44]["Home Goals"]

goal_type_counts = {
    "Normal": 0,
    "Penalty": 0,
    "Own Goal": 0
}

special_goals = []

for match_id, match in enumerate(all_matches, 1):

    for side in ["Home Goals", "Away Goals"]:

        for goal in match[side]:

            goal_type = goal["Goal Type"]

            goal_type_counts[goal_type] += 1

            if goal_type != "Normal":
                special_goals.append({
                    "Match ID": match_id,
                    "Player": goal["Player"],
                    "Minute": goal["Minute"],
                    "Goal Type": goal_type
                })


print("Goal Type Counts:")
print(goal_type_counts)

print("\nTotal Goals:")
print(sum(goal_type_counts.values()))

print("\nSpecial Goals:")
for goal in special_goals:
    print(goal)

goals_records = []

for match_id, match in enumerate(all_matches, 1):

    # Home Goals
    for goal in match["Home Goals"]:
        goals_records.append({
            "Match ID": match_id,
            "Date": match["Date"],
            "Stage": match["Stage"],
            "Team": match["Home Team"],
            "Opponent": match["Away Team"],
            "Home/Away": "Home",
            "Player": goal["Player"],
            "Minute": goal["Minute"],
            "Goal Type": goal["Goal Type"],
            "Player URL": goal["URL"],
            "Score": match["Score"]
        })

    # Away Goals
    for goal in match["Away Goals"]:
        goals_records.append({
            "Match ID": match_id,
            "Date": match["Date"],
            "Stage": match["Stage"],
            "Team": match["Away Team"],
            "Opponent": match["Home Team"],
            "Home/Away": "Away",
            "Player": goal["Player"],
            "Minute": goal["Minute"],
            "Goal Type": goal["Goal Type"],
            "Player URL": goal["URL"],
            "Score": match["Score"]
        })


goals_df = pd.DataFrame(goals_records)

print("Total goals:", len(goals_df))

print("\nGoal Types:")
print(goals_df["Goal Type"].value_counts())

goals_df.head(10)

goals_df["Player Team"] = goals_df.apply(
    lambda row: (
        row["Opponent"]
        if row["Goal Type"] == "Own Goal"
        else row["Team"]
    ),
    axis=1
)

goals_df["Counts as Player Goal"] = (
    goals_df["Goal Type"] != "Own Goal"
)

goals_df[
    goals_df["Goal Type"] == "Own Goal"
][
    [
        "Match ID",
        "Team",
        "Opponent",
        "Player",
        "Player Team",
        "Goal Type",
        "Counts as Player Goal"
    ]
].head(10)

players_df = (
    goals_df[
        [
            "Player",
            "Player URL",
            "Player Team"
        ]
    ]
    .drop_duplicates(subset=["Player URL"])
    .reset_index(drop=True)
)

print("Unique Players:", len(players_df))
print("Missing URLs:", players_df["Player URL"].isna().sum())

players_df.head(20)

print("Unique Players:", len(players_df))
print("Missing URLs:", players_df["Player URL"].isna().sum())

url_name_check = (
    goals_df.groupby("Player URL")["Player"]
    .nunique()
    .sort_values(ascending=False)
)

problems = url_name_check[url_name_check > 1]

print("URLs with multiple player names:", len(problems))
print(problems)

url_name_check = (
    goals_df.groupby("Player URL")["Player"]
    .nunique()
    .sort_values(ascending=False)
)

problems = url_name_check[url_name_check > 1]

print("URLs with multiple player names:", len(problems))

problems

problem_urls = problems.index.tolist()

for url in problem_urls:
    names = (
        goals_df.loc[
            goals_df["Player URL"] == url,
            "Player"
        ]
        .drop_duplicates()
        .tolist()
    )

    print("URL:", url)
    print("Names:", names)
    print("-" * 50)

goals_df["Player ID"] = goals_df["Player URL"]

players_df["Player ID"] = players_df["Player URL"]

print("Unique Player IDs:", goals_df["Player ID"].nunique())
print("Players Table Rows:", len(players_df))

import requests
from bs4 import BeautifulSoup

first_player_url = players_df.loc[0, "Player URL"]

response = requests.get(
    first_player_url,
    headers={
        "User-Agent": "Mozilla/5.0"
    },
    timeout=20
)

player_soup = BeautifulSoup(response.text, "html.parser")

print("Status:", response.status_code)
print("URL:", first_player_url)

infobox = player_soup.find("table", class_="infobox")

print("Infobox found:", infobox is not None)

for i, row in enumerate(infobox.find_all("tr")):
    header = row.find("th")
    value = row.find("td")

    if header and value:
        print(
            i,
            "|",
            repr(header.get_text(" ", strip=True)),
            "->",
            repr(value.get_text(" ", strip=True))
        )

arabic_months = {
    "يناير": "01",
    "فبراير": "02",
    "مارس": "03",
    "أبريل": "04",
    "مايو": "05",
    "يونيو": "06",
    "يوليو": "07",
    "أغسطس": "08",
    "سبتمبر": "09",
    "أكتوبر": "10",
    "نوفمبر": "11",
    "ديسمبر": "12"
}


def get_infobox_value(infobox, label):
    for row in infobox.find_all("tr"):
        header = row.find("th")
        value = row.find("td")

        if header and value:
            header_text = clean_unicode_text(
                header.get_text(" ", strip=True)
            )

            if header_text == label:
                return clean_unicode_text(
                    value.get_text(" ", strip=True)
                )

    return None


# Official player name
name_tag = player_soup.find("h1")

official_name = (
    clean_unicode_text(name_tag.get_text(" ", strip=True))
    if name_tag
    else None
)


# Date of Birth
birth_text = get_infobox_value(
    infobox,
    "تاريخ الميلاد"
)

birth_date = None

if birth_text:
    birth_match = re.search(
        r"(\d{1,2})\s+([^\s]+)\s+(\d{4})",
        birth_text
    )

    if birth_match:
        day = int(birth_match.group(1))
        month_name = birth_match.group(2)
        year = birth_match.group(3)

        month = arabic_months.get(month_name)

        if month:
            birth_date = f"{day:02d}/{month}/{year}"


# Citizenship
citizenship = get_infobox_value(
    infobox,
    "مواطنة"
)


# Position
position = get_infobox_value(
    infobox,
    "مركز اللعب"
)


# Height
height_text = get_infobox_value(
    infobox,
    "الطول"
)

height_cm = None

if height_text:
    height_match = re.search(r"\d+", height_text)

    if height_match:
        height_cm = int(height_match.group())


player_record = {
    "Player Name": official_name,
    "Date of Birth": birth_date,
    "Citizenship": citizenship,
    "Position": position,
    "Height CM": height_cm,
    "Player URL": first_player_url
}

player_record

def clean_infobox_text(text):
    if text is None:
        return None

    text = clean_unicode_text(text)

    # Remove things like [لغات أخرى]
    text = re.sub(r"\[[^\]]*\]", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

position = clean_infobox_text(
    get_infobox_value(
        infobox,
        "مركز اللعب"
    )
)

print(position)

def parse_player_page(player_url):
    try:
        response = requests.get(
            player_url,
            headers={
                "User-Agent": "Mozilla/5.0"
            },
            timeout=20
        )

        if response.status_code != 200:
            return None

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        infobox = soup.find(
            "table",
            class_="infobox"
        )

        if infobox is None:
            return None

        # -------------------------
        # Official Name
        # -------------------------
        name_tag = soup.find("h1")

        player_name = (
            clean_unicode_text(
                name_tag.get_text(" ", strip=True)
            )
            if name_tag
            else None
        )

        # -------------------------
        # Date of Birth
        # -------------------------
        birth_text = get_infobox_value(
            infobox,
            "تاريخ الميلاد"
        )

        birth_date = None

        if birth_text:
            birth_match = re.search(
                r"(\d{1,2})\s+([^\s]+)\s+(\d{4})",
                birth_text
            )

            if birth_match:
                day = int(birth_match.group(1))
                month_name = birth_match.group(2)
                year = birth_match.group(3)

                month = arabic_months.get(
                    month_name
                )

                if month:
                    birth_date = (
                        f"{day:02d}/{month}/{year}"
                    )

        # -------------------------
        # Citizenship
        # -------------------------
        citizenship = clean_infobox_text(
            get_infobox_value(
                infobox,
                "مواطنة"
            )
        )

        # -------------------------
        # Position
        # -------------------------
        position = clean_infobox_text(
            get_infobox_value(
                infobox,
                "مركز اللعب"
            )
        )

        # -------------------------
        # Height
        # -------------------------
        height_text = get_infobox_value(
            infobox,
            "الطول"
        )

        height_cm = None

        if height_text:
            height_match = re.search(
                r"\d+",
                height_text
            )

            if height_match:
                height_cm = int(
                    height_match.group()
                )

        return {
            "Player ID": player_url,
            "Player Name": player_name,
            "Date of Birth": birth_date,
            "Citizenship": citizenship,
            "Position": position,
            "Height CM": height_cm,
            "Player URL": player_url
        }

    except Exception as e:
        print(
            "Error:",
            player_url,
            "->",
            e
        )

        return None

test_player = parse_player_page(
    players_df.loc[0, "Player URL"]
)

test_player

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

session = requests.Session()

session.headers.update({
    "User-Agent": "Mozilla/5.0"
})

retry_strategy = Retry(
    total=2,
    connect=2,
    read=2,
    backoff_factor=0.5,
    status_forcelist=[429, 500, 502, 503, 504]
)

adapter = HTTPAdapter(
    max_retries=retry_strategy,
    pool_connections=10,
    pool_maxsize=10
)

session.mount("https://", adapter)

response = requests.get(
    player_url,
    headers={
        "User-Agent": "Mozilla/5.0"
    },
    timeout=20
)

response = session.get(
    player_url,
    timeout=(5, 10)
)

processed_ids = {
    record["Player ID"]
    for record in player_records
}

print("Already extracted:", len(processed_ids))

total_players = len(players_df)

for i, row in players_df.iterrows():

    player_url = row["Player URL"]

    # Skip players already extracted
    if player_url in processed_ids:
        continue

    print(
        f"{i + 1}/{total_players}",
        "-",
        row["Player"]
    )

    record = parse_player_page(player_url)

    if record is not None:
        player_records.append(record)
        processed_ids.add(player_url)

    else:
        failed_players.append({
            "Player": row["Player"],
            "Player URL": player_url
        })

    time.sleep(0.2)


player_details_df = pd.DataFrame(player_records)

print("\n--------------------")
print("Players expected:", total_players)
print("Players extracted:", len(player_details_df))
print("Failed:", len(failed_players))

stadium_records = []

for row in real_match_rows:
    footballbox = row.find_parent("div", class_="footballbox")
    fleft = footballbox.find("div", class_="fleft")

    if not fleft:
        continue

    details = fleft.find_all("div", recursive=False)

    if not details:
        continue

    venue_links = details[0].find_all("a")

    stadium = (
        venue_links[0].get_text(" ", strip=True)
        if len(venue_links) >= 1
        else None
    )

    stadium_url = (
        venue_links[0].get("href")
        if len(venue_links) >= 1
        else None
    )

    city = (
        venue_links[1].get_text(" ", strip=True)
        if len(venue_links) >= 2
        else None
    )

    stadium_records.append({
        "Stadium": stadium,
        "City": city,
        "Stadium URL": stadium_url
    })


stadiums_df = (
    pd.DataFrame(stadium_records)
    .drop_duplicates(subset=["Stadium URL"])
    .reset_index(drop=True)
)

print("Unique Stadiums:", len(stadiums_df))
print("Missing URLs:", stadiums_df["Stadium URL"].isna().sum())

stadiums_df

from urllib.parse import urljoin
import re
import pandas as pd

def parse_capacity(stadium_url):

    # Make sure URL is absolute
    stadium_url = urljoin(
        "https://ar.wikipedia.org",
        stadium_url
    )

    try:
        response = session.get(
            stadium_url,
            timeout=(5, 10)
        )

        if response.status_code != 200:
            return None

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        infobox = soup.find(
            "table",
            class_="infobox"
        )

        if infobox is None:
            return None

        for row in infobox.find_all("tr"):

            header = row.find("th")
            value = row.find("td")

            if not header or not value:
                continue

            header_text = clean_infobox_text(
                header.get_text(" ", strip=True)
            )

            # Search for capacity field
            if header_text and "السعة" in header_text:

                capacity_text = clean_infobox_text(
                    value.get_text(" ", strip=True)
                )

                # Remove commas
                capacity_text = capacity_text.replace(",", "")

                numbers = re.findall(
                    r"\d+",
                    capacity_text
                )

                if numbers:
                    return int(numbers[0])

        return None

    except Exception as e:
        print(
            "Error:",
            stadium_url,
            "->",
            e
        )

        return None

capacities = []

for i, row in stadiums_df.iterrows():

    print(
        f"{i + 1}/{len(stadiums_df)}",
        "-",
        row["Stadium"]
    )

    capacity = parse_capacity(
        row["Stadium URL"]
    )

    capacities.append(capacity)


stadiums_df["Capacity"] = capacities


print("\n--------------------")
print("Total Stadiums:", len(stadiums_df))
print(
    "Capacities Found:",
    stadiums_df["Capacity"].notna().sum()
)
print(
    "Missing Capacities:",
    stadiums_df["Capacity"].isna().sum()
)

stadiums_df

tables = stadium_soup.find_all("table")

print("Number of tables:", len(tables))

for i, table in enumerate(tables[:15]):
    print(
        i,
        "->",
        table.get("class")
    )

page_text = stadium_soup.get_text(" ", strip=True)

keywords = [
    "السعة",
    "سعة",
    "استيعاب",
    "متفرج",
    "مقعد"
]

for keyword in keywords:
    if keyword in page_text:
        print("FOUND:", keyword)

        pos = page_text.find(keyword)

        print(
            page_text[
                max(0, pos - 150):
                pos + 250
            ]
        )

        print("-" * 80)

def parse_capacity(stadium_url):

    stadium_url = urljoin(
        "https://ar.wikipedia.org",
        stadium_url
    )

    try:
        response = session.get(
            stadium_url,
            timeout=(5, 10)
        )

        if response.status_code != 200:
            return None

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        page_text = clean_unicode_text(
            soup.get_text(" ", strip=True)
        )

        patterns = [
            r"الطاقة\s+الاستيعابية\s+([\d,٬]+)",
            r"السعة\s+الاستيعابية\s+([\d,٬]+)",
            r"السعة\s+([\d,٬]+)"
        ]

        for pattern in patterns:

            match = re.search(pattern, page_text)

            if match:
                number = match.group(1)

                number = (
                    number
                    .replace(",", "")
                    .replace("٬", "")
                )

                return int(number)

        return None

    except Exception as e:
        print(
            "Error:",
            stadium_url,
            "->",
            e
        )

        return None

capacities = []

for i, row in stadiums_df.iterrows():

    print(
        f"{i + 1}/{len(stadiums_df)}",
        "-",
        row["Stadium"]
    )

    capacity = parse_capacity(
        row["Stadium URL"]
    )

    capacities.append(capacity)


stadiums_df["Capacity"] = capacities


print("\n--------------------")
print("Total Stadiums:", len(stadiums_df))
print(
    "Capacities Found:",
    stadiums_df["Capacity"].notna().sum()
)
print(
    "Missing Capacities:",
    stadiums_df["Capacity"].isna().sum()
)

stadiums_df[
    ["Stadium", "City", "Capacity"]
]

print("Players:", len(player_details_df))

print("\nMissing Player Data:")
print(
    player_details_df[
        [
            "Player Name",
            "Date of Birth",
            "Citizenship",
            "Position",
            "Height CM"
        ]
    ].isna().sum()
)

player_details_df = player_details_df.drop(
    columns=["Date of Birth"],
    errors="ignore"
)

print("Players:", len(player_details_df))

print("\nMissing Player Data:")
print(
    player_details_df[
        [
            "Player Name",
            "Citizenship",
            "Position",
            "Height CM"
        ]
    ].isna().sum()
)

player_details_df = player_details_df.drop(
    columns=["Citizenship"],
    errors="ignore"
)

print("Players:", len(player_details_df))

print("\nMissing Player Data:")
print(
    player_details_df[
        [
            "Player Name",
            "Position",
            "Height CM"
        ]
    ].isna().sum()
)

missing_players = player_details_df[
    player_details_df[
        ["Position", "Height CM"]
    ].isna().any(axis=1)
]

missing_players[
    [
        "Player Name",
        "Position",
        "Height CM",
        "Player URL"
    ]
]

missing_positions = {
    "ماتيو شافييز": "ظهير أيسر",
    "إرمين محميتش": "وسط هجومي",
    "ناثانيال براون (لاعب كرة قدم)": "ظهير أيسر",
    "هيليو فاريلا": "جناح أيسر",
    "ثيلو أسغارد": "وسط هجومي",
    "سيدني لوبيز كابرال": "ظهير أيسر"
}

for player, position in missing_positions.items():
    player_details_df.loc[
        player_details_df["Player Name"] == player,
        "Position"
    ] = position

print(
    "Missing Positions:",
    player_details_df["Position"].isna().sum()
)

player_details_df[
    player_details_df["Player Name"].isin(
        missing_positions.keys()
    )
][
    ["Player Name", "Position"]
]

player_details_df = player_details_df.drop(
    columns=["Height CM"],
    errors="ignore"
)

print(player_details_df.columns)

# =========================
# 1) MATCHES TABLE
# =========================

matches_final = pd.DataFrame(all_matches).copy()

# Remove nested goal lists because Goals has its own table
matches_final = matches_final.drop(
    columns=["Home Goals", "Away Goals"],
    errors="ignore"
)

# Add Match ID
matches_final.insert(
    0,
    "Match ID",
    range(1, len(matches_final) + 1)
)


# =========================
# 2) GOALS TABLE
# =========================

goals_final = goals_df.copy()


# =========================
# 3) PLAYERS TABLE
# =========================

players_final = player_details_df.copy()


# =========================
# 4) STADIUMS TABLE
# =========================

stadiums_final = stadiums_df.copy()

stadiums_final.insert(
    0,
    "Stadium ID",
    range(1, len(stadiums_final) + 1)
)


# =========================
# FINAL CHECK
# =========================

print("Matches:", len(matches_final))
print("Goals:", len(goals_final))
print("Players:", len(players_final))
print("Stadiums:", len(stadiums_final))

# =========================
# FINAL RELATIONSHIPS
# =========================

# Stadium ID map
stadium_id_map = dict(
    zip(
        stadiums_final["Stadium"],
        stadiums_final["Stadium ID"]
    )
)

matches_final["Stadium ID"] = (
    matches_final["Stadium"].map(stadium_id_map)
)

# =========================
# CONVERT DATE
# =========================

matches_final["Date"] = pd.to_datetime(
    matches_final["Date"],
    format="%d/%m/%Y"
)

goals_final["Date"] = pd.to_datetime(
    goals_final["Date"],
    format="%d/%m/%Y"
)

# =========================
# FINAL VALIDATION
# =========================

print("Matches:", len(matches_final))
print("Goals:", len(goals_final))
print("Players:", len(players_final))
print("Stadiums:", len(stadiums_final))

print(
    "Missing Stadium IDs:",
    matches_final["Stadium ID"].isna().sum()
)

print(
    "Missing Player IDs:",
    goals_final["Player ID"].isna().sum()
)

# =========================
# EXPORT TO EXCEL
# =========================

output_file = "/content/World_Cup_2026_Final.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="xlsxwriter",
    datetime_format="dd/mm/yyyy"
) as writer:

    matches_final.to_excel(
        writer,
        sheet_name="Matches",
        index=False
    )

    goals_final.to_excel(
        writer,
        sheet_name="Goals",
        index=False
    )

    players_final.to_excel(
        writer,
        sheet_name="Players",
        index=False
    )

    stadiums_final.to_excel(
        writer,
        sheet_name="Stadiums",
        index=False
    )

    # Basic formatting
    workbook = writer.book

    for sheet_name, df in {
        "Matches": matches_final,
        "Goals": goals_final,
        "Players": players_final,
        "Stadiums": stadiums_final
    }.items():

        worksheet = writer.sheets[sheet_name]

        worksheet.freeze_panes(1, 0)
        worksheet.autofilter(
            0,
            0,
            len(df),
            len(df.columns) - 1
        )

        worksheet.set_column(
            0,
            len(df.columns) - 1,
            18
        )

print("\nExcel created:")
print(output_file)

def normalize_stadium_name(x):
    if pd.isna(x):
        return None

    x = clean_unicode_text(str(x))
    x = re.sub(r"\s+", " ", x).strip()

    return x


# Create normalized names
matches_final["_Stadium Key"] = (
    matches_final["Stadium"].apply(normalize_stadium_name)
)

stadiums_final["_Stadium Key"] = (
    stadiums_final["Stadium"].apply(normalize_stadium_name)
)


# Rebuild mapping
stadium_id_map = dict(
    zip(
        stadiums_final["_Stadium Key"],
        stadiums_final["Stadium ID"]
    )
)

matches_final["Stadium ID"] = (
    matches_final["_Stadium Key"].map(stadium_id_map)
)


print(
    "Missing Stadium IDs:",
    matches_final["Stadium ID"].isna().sum()
)

print(
    matches_final.loc[
        matches_final["Stadium ID"].isna(),
        ["Match ID", "Stadium"]
    ]
)

def normalize_stadium_name(x):
    if pd.isna(x):
        return None

    x = clean_unicode_text(str(x))
    x = re.sub(r"\s+", " ", x).strip()

    # Remove leading "ملعب" only for matching
    x = re.sub(r"^ملعب\s+", "", x)

    return x


matches_final["_Stadium Key"] = (
    matches_final["Stadium"].apply(normalize_stadium_name)
)

stadiums_final["_Stadium Key"] = (
    stadiums_final["Stadium"].apply(normalize_stadium_name)
)

stadium_id_map = dict(
    zip(
        stadiums_final["_Stadium Key"],
        stadiums_final["Stadium ID"]
    )
)

matches_final["Stadium ID"] = (
    matches_final["_Stadium Key"].map(stadium_id_map)
)

print(
    "Missing Stadium IDs:",
    matches_final["Stadium ID"].isna().sum()
)

# Remove temporary helper columns if they still exist
matches_final = matches_final.drop(
    columns=["_Stadium Key"],
    errors="ignore"
)

stadiums_final = stadiums_final.drop(
    columns=["_Stadium Key"],
    errors="ignore"
)

output_file = "/content/World_Cup_2026_Final.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    matches_final.to_excel(
        writer,
        sheet_name="Matches",
        index=False
    )

    goals_final.to_excel(
        writer,
        sheet_name="Goals",
        index=False
    )

    players_final.to_excel(
        writer,
        sheet_name="Players",
        index=False
    )

    stadiums_final.to_excel(
        writer,
        sheet_name="Stadiums",
        index=False
    )

print("Excel created successfully:")
print(output_file)

from google.colab import files

files.download("/content/World_Cup_2026_Final.xlsx")

# =========================
# CREATE NUMERIC PLAYER ID
# =========================

players_final = player_details_df.copy().reset_index(drop=True)

# Create IDs: 1 to 191
players_final["Player ID"] = range(
    1,
    len(players_final) + 1
)

# URL -> Player ID mapping
player_id_map = dict(
    zip(
        players_final["Player URL"],
        players_final["Player ID"]
    )
)

# Apply same Player ID to Goals
goals_final["Player ID"] = (
    goals_final["Player URL"]
    .map(player_id_map)
)

# Reorder Players table
players_final = players_final[
    [
        "Player ID",
        "Player Name",
        "Position",
        "Player URL"
    ]
]

print("Players:", len(players_final))
print(
    "Unique Player IDs:",
    players_final["Player ID"].nunique()
)
print(
    "Missing Player IDs in Goals:",
    goals_final["Player ID"].isna().sum()
)

from urllib.parse import urlparse, unquote
import requests
import time

# Extract Wikipedia page title from URL
def get_wiki_title(url):
    path = urlparse(url).path
    title = path.split("/wiki/")[-1]
    return unquote(title).replace("_", " ")


players_final["Wiki Title"] = (
    players_final["Player URL"]
    .apply(get_wiki_title)
)

titles = players_final["Wiki Title"].tolist()

image_map = {}

# Wikipedia API - batches of 50 players
for start in range(0, len(titles), 50):

    batch = titles[start:start + 50]

    params = {
        "action": "query",
        "format": "json",
        "prop": "pageimages",
        "piprop": "original|thumbnail",
        "pithumbsize": 500,
        "titles": "|".join(batch)
    }

    response = session.get(
        "https://ar.wikipedia.org/w/api.php",
        params=params,
        timeout=(5, 15)
    )

    data = response.json()

    for page in data["query"]["pages"].values():

        title = page.get("title")

        image_url = None

        if "thumbnail" in page:
            image_url = page["thumbnail"]["source"]

        elif "original" in page:
            image_url = page["original"]["source"]

        image_map[title] = image_url

    print(
        f"Processed {min(start + 50, len(titles))}/{len(titles)}"
    )

    time.sleep(0.3)


players_final["Player Image URL"] = (
    players_final["Wiki Title"]
    .map(image_map)
)

print(
    "Players:",
    len(players_final)
)

print(
    "Images Found:",
    players_final["Player Image URL"].notna().sum()
)

print(
    "Missing Images:",
    players_final["Player Image URL"].isna().sum()
)

from urllib.parse import urljoin
import time

# Show missing players first
missing_images = players_final[
    players_final["Player Image URL"].isna()
]

print("Missing Players:", len(missing_images))
print(
    missing_images[
        ["Player ID", "Player Name", "Player URL"]
    ]
)

for idx, row in players_final[
    players_final["Player Image URL"].isna()
].iterrows():

    print(
        row["Player ID"],
        "-",
        row["Player Name"]
    )

    image_url = get_player_image_fallback(
        row["Player URL"]
    )

    players_final.loc[
        idx,
        "Player Image URL"
    ] = image_url

    time.sleep(0.2)


print("\nImages Found:",
      players_final["Player Image URL"].notna().sum())

print("Missing Images:",
      players_final["Player Image URL"].isna().sum())

from urllib.parse import urljoin

def get_player_image_fallback(player_url):
    try:
        response = session.get(
            player_url,
            timeout=(5, 10)
        )

        if response.status_code != 200:
            return None

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # Try infobox image
        infobox = soup.find(
            "table",
            class_="infobox"
        )

        if infobox:
            img = infobox.find("img")

            if img:
                src = img.get("src")

                if src:
                    return urljoin(
                        "https://ar.wikipedia.org",
                        src
                    )

        # Fallback: OpenGraph image
        og_image = soup.find(
            "meta",
            property="og:image"
        )

        if og_image:
            return og_image.get("content")

        return None

    except Exception as e:
        print("Error:", player_url, "->", e)
        return None

for idx, row in players_final[
    players_final["Player Image URL"].isna()
].iterrows():

    print(
        row["Player ID"],
        "-",
        row["Player Name"]
    )

    image_url = get_player_image_fallback(
        row["Player URL"]
    )

    players_final.loc[
        idx,
        "Player Image URL"
    ] = image_url

    time.sleep(0.2)


print(
    "\nImages Found:",
    players_final["Player Image URL"].notna().sum()
)

print(
    "Missing Images:",
    players_final["Player Image URL"].isna().sum()
)

# ==========================================
# 1) FINAL PLAYER IDs
# ==========================================

players_final = players_final.reset_index(drop=True)

# Numeric Player IDs
players_final["Player ID"] = range(
    1,
    len(players_final) + 1
)

# Map Wikipedia URL -> Numeric ID
player_id_map = dict(
    zip(
        players_final["Player URL"],
        players_final["Player ID"]
    )
)

# Same ID in Goals
goals_final["Player ID"] = (
    goals_final["Player URL"]
    .map(player_id_map)
    .astype("Int64")
)


# ==========================================
# 2) CLEAN PLAYERS TABLE
# ==========================================

players_final = players_final[
    [
        "Player ID",
        "Player Name",
        "Position",
        "Player Image URL"
    ]
]


# ==========================================
# 3) REMOVE PLAYER URL FROM GOALS
# ==========================================

goals_final = goals_final.drop(
    columns=["Player URL"],
    errors="ignore"
)


# ==========================================
# 4) REMOVE DATE TIME
# ==========================================

matches_final["Date"] = pd.to_datetime(
    matches_final["Date"]
).dt.date

goals_final["Date"] = pd.to_datetime(
    goals_final["Date"]
).dt.date


# ==========================================
# 5) REMOVE ANY TEMP COLUMNS
# ==========================================

matches_final = matches_final.drop(
    columns=["_Stadium Key"],
    errors="ignore"
)

stadiums_final = stadiums_final.drop(
    columns=["_Stadium Key"],
    errors="ignore"
)


# ==========================================
# 6) FINAL VALIDATION
# ==========================================

print("Matches:", len(matches_final))
print("Goals:", len(goals_final))
print("Players:", len(players_final))
print("Stadiums:", len(stadiums_final))

print(
    "Missing Player IDs:",
    goals_final["Player ID"].isna().sum()
)

print(
    "Missing Player Images:",
    players_final["Player Image URL"].isna().sum()
)

print(
    "Missing Stadium IDs:",
    matches_final["Stadium ID"].isna().sum()
)


# ==========================================
# 7) EXPORT FINAL EXCEL
# ==========================================

output_file = "/content/World_Cup_2026_Final_v2.xlsx"

with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    matches_final.to_excel(
        writer,
        sheet_name="Matches",
        index=False
    )

    goals_final.to_excel(
        writer,
        sheet_name="Goals",
        index=False
    )

    players_final.to_excel(
        writer,
        sheet_name="Players",
        index=False
    )

    stadiums_final.to_excel(
        writer,
        sheet_name="Stadiums",
        index=False
    )


# ==========================================
# 8) DOWNLOAD
# ==========================================

from google.colab import files

print("\nFinal Excel created:")
print(output_file)

files.download(output_file)

attendance

import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

url = "https://ar.wikipedia.org/wiki/كأس_العالم_2026"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print("Status Code:", response.status_code)

soup = BeautifulSoup(response.text, "html.parser")

# Find all match boxes
match_boxes = soup.select(".footballbox")

print("Football boxes found:", len(match_boxes))

# Show the first match as a test
if match_boxes:
    print("\n--- FIRST MATCH ---")
    print(
        match_boxes[0].get_text(
            " | ",
            strip=True
        )
    )

records = []

for i, box in enumerate(match_boxes, start=1):
    text = box.get_text(" | ", strip=True)

    # teams
    home = box.select_one(".fhome")
    away = box.select_one(".faway")

    home_team = home.get_text(" ", strip=True) if home else None
    away_team = away.get_text(" ", strip=True) if away else None

    # raw attendance text
    match = re.search(r"الحضور:\s*([\d,٬]+)", text)
    raw_attendance = match.group(1) if match else None

    records.append({
        "Match ID": i,
        "Home Team": home_team,
        "Away Team": away_team,
        "Raw Attendance": raw_attendance
    })

attendance_df = pd.DataFrame(records)

print("Rows:", len(attendance_df))
print("Missing Attendance:", attendance_df["Raw Attendance"].isna().sum())
print()
print(attendance_df.head(10).to_string(index=False))

# Show all suspicious attendance values below 1000

for i, box in enumerate(match_boxes, start=1):

    text = box.get_text(" | ", strip=True)

    match = re.search(r"الحضور:\s*([\d,٬]+)", text)

    if match:
        raw_attendance = match.group(1)

        numeric_attendance = int(
            raw_attendance
            .replace(",", "")
            .replace("٬", "")
        )

        if numeric_attendance < 1000:

            home = box.select_one(".fhome")
            away = box.select_one(".faway")
            stadium = box.select_one(".fstadium")

            print("=" * 70)
            print("Match ID:", i)

            print(
                "Home:",
                home.get_text(" ", strip=True)
                if home else None
            )

            print(
                "Away:",
                away.get_text(" ", strip=True)
                if away else None
            )

            print(
                "Stadium:",
                stadium.get_text(" ", strip=True)
                if stadium else None
            )

            print(
                "Raw Attendance:",
                raw_attendance
            )

            print("\nFULL MATCH TEXT:")
            print(text)

records = []

for i, box in enumerate(match_boxes, start=1):

    text = box.get_text(" | ", strip=True)

    home = box.select_one(".fhome")
    away = box.select_one(".faway")

    home_team = home.get_text(" ", strip=True) if home else None
    away_team = away.get_text(" ", strip=True) if away else None

    # Supports:
    # 80,824
    # 80٬824
    # 80،824
    match = re.search(
        r"الحضور:\s*([\d,٬،]+)",
        text
    )

    raw_attendance = match.group(1) if match else None

    attendance = (
        int(
            raw_attendance
            .replace(",", "")
            .replace("٬", "")
            .replace("،", "")
        )
        if raw_attendance
        else None
    )

    records.append({
        "Match ID": i,
        "Home Team": home_team,
        "Away Team": away_team,
        "Raw Attendance": raw_attendance,
        "Attendance": attendance
    })

attendance_df = pd.DataFrame(records)

print("Rows:", len(attendance_df))
print("Missing:", attendance_df["Attendance"].isna().sum())

print()
print(attendance_df.head(10).to_string(index=False))

suspicious = attendance_df[
    attendance_df["Attendance"] < 1000
]

print("Suspicious rows:", len(suspicious))

if len(suspicious) > 0:
    print(suspicious.to_string(index=False))
else:
    print("All attendance values look valid ✅")

print("Total Attendance:", attendance_df["Attendance"].sum())
print("Average Attendance:", round(attendance_df["Attendance"].mean(), 2))
print("Minimum Attendance:", attendance_df["Attendance"].min())
print("Maximum Attendance:", attendance_df["Attendance"].max())

attendance_only_df = attendance_df[["Attendance"]]

attendance_only_df.to_excel(
    "World_Cup_2026_Attendance.xlsx",
    index=False
)

print("Excel file created ✅")

from google.colab import files

files.download("World_Cup_2026_Attendance.xlsx")